
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef COMMSYS_H
#define COMMSYS_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 commsys_valueRangeTest (UNS8 typeValue, void * value);
const indextable * commsys_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data commsys_Data;
extern UNS8 Receive[100];		/* Mapped at index 0x2000, subindex 0x00*/

#endif // COMMSYS_H
