
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef NAVSYSTEM_H
#define NAVSYSTEM_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 navsystem_valueRangeTest (UNS8 typeValue, void * value);
const indextable * navsystem_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data navsystem_Data;
extern UNS8 Send[100];		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 Receive[100];		/* Mapped at index 0x2001, subindex 0x00*/

#endif // NAVSYSTEM_H
