
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SIMPLEMASTER_H
#define SIMPLEMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 simplemaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * simplemaster_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data simplemaster_Data;

#endif // SIMPLEMASTER_H
