
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SIMPLEAPP_H
#define SIMPLEAPP_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 simpleapp_valueRangeTest (UNS8 typeValue, void * value);
const indextable * simpleapp_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data simpleapp_Data;
extern UNS8 dns_primary[20];		/* Mapped at index 0x500B, subindex 0x00*/

#endif // SIMPLEAPP_H
